### ISSUE TITLE
SetEditor examples

### ISSUE THREAD

**Issue by hillsydev** [MatthewKing/DynamicDescriptors#2]
Do you have some examples of how to use the SetEditor?  I have populated the dynamic properties from a dictionary but using SetEditor doesn't appear to work.  Using .net framework 4.8

**Comment by MatthewKing** [comment]
Sure.

Let's say we have an example class:

```csharp
class ExampleClass
{
    public string Value { get; set; }
}
```

Then we can set a custom editor on the `Value` property like so:

```csharp
var instance = new ExampleClass();
var descriptor = DynamicDescriptor.CreateFromInstance(instance);
descriptor.GetDynamicProperty(nameof(ExampleClass.Value))
    .SetEditor(typeof(UITypeEditor), new MultilineStringEditor());
```

**Comment by hillsydev** [comment]
> Sure.
> 
> Let's say we have an example class:
> 
> ```cs
> class ExampleClass
> {
>     public string Value { get; set; }
> }
> ```
> 
> Then we can set a custom editor on the `Value` property like so:
> 
> ```cs
> var instance = new ExampleClass();
> var descriptor = DynamicDescriptor.CreateFromInstance(instance);
> descriptor.GetDynamicProperty(nameof(ExampleClass.Value))
>     .SetEditor(typeof(UITypeEditor), new MultilineStringEditor());
> ```

Perfect, that was exactly what I was looking for.  Great work, thank you!
